---
# EE definition for running VMware automation

# builder schema version
version: 3

images:
  # build a new image based on this image
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  # version of ansible-core
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner
  # collections to install from galaxy
  galaxy:
    - community.vmware
    - vmware.vmware_rest
  # python packages, stuff you install with 'pip install'
  python:
    - six
    - pyvmomi
  # system packages, stuff you install with 'apt install'
  system: 
    - bindep.txt
    - python3-dnf
additional_build_steps:
  # items in the list of append_base steps are expressed
  # as containerfile directives
  append_base:
    - RUN dnf install git -y
