---
# EE definition for general PUL automation

# builder schema version
version: 3

images:
  # build a new image based on this image
  base_image:
    name: quay.io/centos/centos:stream9
    
dependencies:
  # version of ansible-core
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner
  # collections to install from galaxy
  # includes all collections used in the prancible repo
  # versions taken from the Ansible 9 inclusion list:
  # https://github.com/ansible-community/ansible-build-data/blob/main/9/ansible-9.1.0.deps
  galaxy:
    - name: ansible.netcommon
      version: 5.3.0
    - name: ansible.posix
      version: 1.5.4
    - name: ansible.utils
      version: 2.12.0
    - name: community.crypto
      version: 2.16.1
    - name: community.dns
      version: 2.6.4
    - name: community.general
      version: 8.1.0
    - name: community.postgresql
      version: 3.2.0
    - name: community.rabbitmq
      version: 1.2.3
    - name: community.vmware
      version: 4.0.1
    - name: google.cloud
      version: 1.3.0
    - name: vmware.vmware_rest
      version: 2.3.1
# not in Ansible 9 package
# latest versions from Galaxy as of Feb. 2024
    - name: servicenow.servicenow
      version: 1.0.6
    - name: paloaltonetworks.panos
      version: 2.19.1

  # python packages, stuff you install with 'pip install'
  python:
    - six
    - psutil
  # system packages, stuff you install with 'apt install'
  system: 
    - bindep.txt
    - python3-dnf
additional_build_steps:
  # items in the list of append_base steps are expressed
  # as containerfile directives
  append_base:
    - RUN dnf install git -y
